title: "forsec"
description: "IT-Security blog"
permalink: /:title/
lang: "en"

dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
dark_theme: false            # use the dark mode as default
show_footer: true            # show the "previous" and "next" links at the end of each post
hide_title: false            # don't show the site title in the header

navigation:                  # site navigation in the header
  - /index.html
  - about.md

plugins:
 - jekyll-feed
 - jekyll-default-layout
